### ISSUE TITLE
Data Description Table

### ISSUE THREAD

**Issue by Lucadilisciandro** [Lucadilisciandro/QMB210-15-Group1#1]
1. Clearly Identify the data that you are discussing.
2. Format your table describing the data.
4. Describe at least 4 data fields as
quantitative/qualitative and which type (nominal, ratio, ordinal,
interval). Show at least one qualitative and one quantitative
5. Clearly identify where the data came from (i.e.
Survey of students living in Morsani Hall, Team 1)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/241ff785-d457-416c-a8f1-d91e48df8220)

**Comment by josephaabreu** [comment]
[Data Description Table.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14620620/Data.Description.Table.xlsx)

**Comment by SamFrieman03** [comment]
This Table Will Be Done By SamFrieman03

**Comment by SamFrieman03** [comment]
[Data Description Table.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14956215/Data.Description.Table.xlsx)
