### ISSUE TITLE
Video Frequency Table #1

### ISSUE THREAD

**Issue by SamFrieman03** [Lucadilisciandro/QMB210-15-Group1#11]
Individual video files

**Comment by joef3rnandez** [comment]
(Video For Frequency Table 1)

**Comment by joef3rnandez** [comment]
[
](https://spartansut-my.sharepoint.com/:v:/g/personal/joseph_fernandez_spartans_ut_edu/EasOYj1_hXxKom4z8cxCtXsBWDMyYmYtiPHu63_uyWuG6A)

**Comment by SamFrieman03** [comment]
Unable to be submitted on GitHub

"Joe F. is the person responsible for this part GitHub will not let me assign him for some reason."
-Sam Frieman
