### ISSUE TITLE
Video Contingency Table #1

### ISSUE THREAD

**Issue by SamFrieman03** [Lucadilisciandro/QMB210-15-Group1#18]
Individual video file

**Comment by LoganSaenz** [comment]
[https://vimeo.com/933547692?share=copy ](url)

**Comment by LoganSaenz** [comment]
[https://vimeo.com/934396162?share=copy](url)

**Comment by LoganSaenz** [comment]
https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/158665979/a1db4dc8-f000-453f-8c79-cf2755015a15
