### ISSUE TITLE
Frequency Table #1

### ISSUE THREAD

**Issue by Lucadilisciandro** [Lucadilisciandro/QMB210-15-Group1#3]
Here are some examples.

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/3059ee16-99fa-4200-aabd-b92b9bea36f7)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/82b33cf1-c40a-41f0-a71a-67d6ac340417)

![Image](https://github.co

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/2ec4799c-bedd-4b20-b976-256cb937403a)

m/Lucadilisciandro/QMB210-15-Group1/assets/159053301/6c228fcb-8bbc-4dab-8742-55c5cb149b7a)

**Comment by josephaabreu** [comment]
[Majors Frequency .xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14595535/Majors.Frequency.xlsx)

`

**Comment by SamFrieman03** [comment]
__

**Comment by SamFrieman03** [comment]
This Table Will Be Done By Joef3rnandez

**Comment by joef3rnandez** [comment]
![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/158978778/2107ef88-9b84-40b2-bccd-7d0c5004aadb)

**Comment by SamFrieman03** [comment]
👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joef3rnandez** [comment]
<img width="1015" alt="Screenshot 2024-04-03 at 12 15 47 PM" src="https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/158978778/b523b315-a0d8-4f58-acdc-b5058e771825">

**Comment by joef3rnandez** [comment]
https://spartansut-my.sharepoint.com/:x:/g/personal/joseph_fernandez_spartans_ut_edu/EXVMxnJyCd1PnlX85ZrP2dQBA7-7YNs3qG0yfIz4aoMxXA?e=Nv6Lds

**Comment by joef3rnandez** [comment]
[Frequency_Table1 Final.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14971211/Frequency_Table1.Final.xlsx)

(Updated Excel File)
