### ISSUE TITLE
Frequency Table #2

### ISSUE THREAD

**Issue by Lucadilisciandro** [Lucadilisciandro/QMB210-15-Group1#4]
![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/93a1959f-ec49-49da-833f-6c945d058bb1)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/e9a50198-6501-4922-8462-680543f77c27)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/96856b22-dd20-4049-8d6a-52ddae351a09)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/c66c17e6-1c27-4aa8-af56-8c955fb794f4)

**Comment by josephaabreu** [comment]
[Frequency Table 2.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14620716/Frequency.Table.2.xlsx)

**Comment by SamFrieman03** [comment]
This Will Be Done By RyanLaroche7

**Comment by RyanLaroche7** [comment]
[Frequency Table 2 QMB Project .xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14730002/Frequency.Table.2.QMB.Project.xlsx)

**Comment by RyanLaroche7** [comment]
[Frequency Table 2 QMB Project UPDATE .xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14809788/Frequency.Table.2.QMB.Project.UPDATE.xlsx)
