### ISSUE TITLE
Contingency Table #1

### ISSUE THREAD

**Issue by Lucadilisciandro** [Lucadilisciandro/QMB210-15-Group1#5]
1. Make sure to have your data logically sorted (i.e if Yr is your column, have it start
with Fresh and end with either senior or Grad.

Here are examples.

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/4b1737eb-8368-4c3d-b1af-71d5ab695081)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/911634fb-9b2c-4f42-ad77-0fecb1f183bd)

**Comment by josephaabreu** [comment]
[Contingency Table #1.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14622268/Contingency.Table.1.xlsx)

**Comment by SamFrieman03** [comment]
This Will Be Done By LoganSaenz

**Comment by LoganSaenz** [comment]
https://spartansut-my.sharepoint.com/:x:/g/personal/logan_saenz_spartans_ut_edu/EQraitWkv99Jngs2t30ybkEByIlU_1rGR8Dl2JO3EzqE5g?e=we8fCs

**Comment by LoganSaenz** [comment]
[https://vimeo.com/933547692?share=copy ](url)

**Comment by LoganSaenz** [comment]
![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/158665979/222459a0-b93c-464d-9402-01d6a8b3ff75)

**Comment by LoganSaenz** [comment]
Whats your grade?
Do you struggle to get the classes you want during registration?
