### ISSUE TITLE
Contingency Table #2

### ISSUE THREAD

**Issue by Lucadilisciandro** [Lucadilisciandro/QMB210-15-Group1#6]
1. Make sure to have your data logically sorted (i.e if Yr is your column, have it start
with Fresh and end with either senior or Grad.

Here are examples.

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/1beba569-0de3-46cf-9d3d-51763cb7f8a8)

![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/422e573d-5105-4e2f-89ef-d77c33b7b0f0)

**Comment by josephaabreu** [comment]
[Con Table ^N2 - Majors and Resolutions.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14622496/Con.Table.N2.-.Majors.and.Resolutions.xlsx)

**Comment by josephaabreu** [comment]
[Contingency Table 2 - Majors and Resolutions.xlsx](https://github.com/Lucadilisciandro/QMB210-15-Group1/files/14625839/Contingency.Table.2.-.Majors.and.Resolutions.xlsx)

**Comment by SamFrieman03** [comment]
This Will Be Done By Lucadilisciandro

**Comment by Lucadilisciandro** [comment]
![Image](https://github.com/Lucadilisciandro/QMB210-15-Group1/assets/159053301/c9eb71b4-88ac-4312-a947-b8c6ddc013a6)
